version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=erasmust_db
      - POSTGRES_USER=erasmust_admin
      - POSTGRES_PASSWORD=Ewj3@jcn_234@!
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_NAME=erasmust_db
      - POSTGRES_USER=erasmust_admin
      - POSTGRES_PASSWORD=Ewj3@jcn_234@!
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_NAME=erasmust_db
      - POSTGRES_USER=erasmust_admin
      - POSTGRES_PASSWORD=Ewj3@jcn_234@!
    depends_on:
      - db
